/**
 * Team Board API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginDto } from '../model/models';
import { RegisterDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get user profile
     * 
     * @endpoint get /auth/profile
     */
    authControllerGetProfile(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Login user
     * 
     * @endpoint post /auth/login
     * @param loginDto 
     */
    authControllerLogin(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Register a new user
     * 
     * @endpoint post /auth/register
     * @param registerDto 
     */
    authControllerRegister(registerDto: RegisterDto, extraHttpRequestParams?: any): Observable<{}>;

}
