/**
 * Team Board API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface TasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create new task
     * 
     * @endpoint post /tasks
     */
    tasksControllerCreate(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /tasks/debug/all
     */
    tasksControllerDebugGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete task
     * 
     * @endpoint delete /tasks/{id}
     * @param id Task ID
     */
    tasksControllerDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get all tasks for current user
     * 
     * @endpoint get /tasks
     */
    tasksControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get task by ID
     * 
     * @endpoint get /tasks/{id}
     * @param id Task ID
     */
    tasksControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /tasks/{id}
     * @param id 
     */
    tasksControllerUpdate(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /tasks/{id}/status
     * @param id 
     */
    tasksControllerUpdateStatus(id: string, extraHttpRequestParams?: any): Observable<{}>;

}
