/**
 * Team Board API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /users
     */
    usersControllerGetAllUsers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /users/dictionary
     */
    usersControllerGetUsersDictionary(extraHttpRequestParams?: any): Observable<{}>;

}
